### ISSUE TITLE
Senran Kagura Bon Appetit ERROR 0x80410136 downloading DLCs and Updates

### ISSUE THREAD

**Issue by DracoParadox** [blastrock/pkgj#80]
Version of firmware: 3.65
Version of PKGj: 0.18

I tried to download the update and dlcs for Senran Kagura Bon Appetit and i keep getting this error
"Download failure: HttpError: HTTP download error 0x80410136"

I already tried closing and opening the app, restarting the download and reloading the config in tai in case the nonpdrm wasnt working properly.

**Comment by DracoParadox** [comment]
I just looked in the Vita Dev error codes and technically the error 0x80410136 is SCE_NET_ERROR_ECONNRESET. I dont know if its related with PKGJ or not.

**Comment by blastrock** [comment]
This means that you lost the connection. Maybe you lost wifi? Also make sure the vita doesn't go to sleep during download.

**Comment by blastrock** [comment]
I hope this is fixed...

**Comment by blastrock** [comment]
You should check your wifi connection, reboot your router maybe, and reboot the vita

**Comment by Mithael** [comment]
Same problem. 
3.60 ENSO
v0.31 PKGj

It worked earlier, allowing me to install Stardew Valley and the comppack. I then tried to download the update for Stardew valley but it was still showing the update notification on the game launch screen. I was able to just download the update the intended way (from the update icon) and Stardew still worked just fine after that.

However, afterwards PKGj would not be able to download any other game, I tried a bunch and they all got to 5% then stopped with the ERROR 0x80410136. I was worried Sony had found a way to ban us or something so I tried PKGi v0.05 and it was able to download the games just fine so it must be something with PKGj.

**Comment by blastrock** [comment]
If anyone can give me a wireshark pcap capture from their router while the vita gets that error, it would help me greatly to solve this.

**Comment by blastrock** [comment]
I finally got this issue myself! This seems to happen with games that have LOTS of folders (like hundreds of them). As I said on another issue, creating a folder is very slow on vita, I don't know why, there's probably an issue somewhere, but not in pkgj. In these cases, the http connection is kept open, but no data is read until all the folders could be created. At some point, the server just drops the connection because the vita is too slow to keep up.

A simple workaround is just to retry the download, as the folder will already be there, it will go much faster. I will see if I can do something for this later.

**Comment by des42** [comment]
How do I fix this error?
